### ISSUE TITLE
Don't show all entities at the first start

### ISSUE THREAD

**Issue by noxhirsch** [PiotrMachowski/Home-Assistant-Taskbar-Menu#1]
Hi,
thank you for this cool app - I really like it!
I encountered one problem really quick: I have at a rough guess 1000 entities - scrolling to the bottom of the menu to edit it took several minutes 😂 Maybe it should start empty? Or at least it should be limited to X entities.

**Comment by PiotrMachowski** [comment]
In v1.0.1.0 I have excluded automations and scripts, then limited the rest to 100 items.
