### ISSUE TITLE
File detected as suspicious by AVAST

### ISSUE THREAD

**Issue by mat4444** [PiotrMachowski/Home-Assistant-Taskbar-Menu#11]
Hello,
I wanted to check your software that seems to be great, but Avast keeps opening pop-ups for suspicious file. (both for the installer and the zip file).
Is there a particular reason it detects your software as suspicious ?
Thanks !

**Comment by PiotrMachowski** [comment]
Hi,
I don't know what made Avast unhappy, it's possible that it detects ~~Bitcoin miner~~ that executables are not signed.

**Comment by mat4444** [comment]
Yes, it's possible...
I just wanted to let you know because I think Avast is quite popular, even though not the best antivirus out here.

**Comment by PiotrMachowski** [comment]
Did it detect anything after installation?

**Comment by Shamshala** [comment]
Don't want to be rude but after Avast acquired AVG the whole company is heading to... Just check it via [VirusTotal](https://www.virustotal.com) and if magority of big names say OK, then add it to whitelist. :slightly_smiling_face:

**Comment by PiotrMachowski** [comment]
Ok, I am closing this issue :)
