### ISSUE TITLE
[Feature Request] - Improve sliders

### ISSUE THREAD

**Issue by mat4444** [PiotrMachowski/Home-Assistant-Taskbar-Menu#12]
Hi,
This is a great and very useful app !
I have a comment to improve usability of sliders, such as when you control a light entity. It would be great if we could click anywhere on the slider to change the brightness or the temperature, like with most interfaces. Currently, we must drag the circle along the line to change it. And even better, if we could use the mouse wheel, but it's perhaps too much to ask ! 
Another comment: it would be great if the entity configuration window did not close right after moving a slider, so as to be able to fine tune it, or change another parameter (light temperature for instance)
Thanks for considering it !

**Comment by PiotrMachowski** [comment]
I have fixed this problem in v1.1.2.0: sliders are "clickable" now
