### ISSUE TITLE
Taskbar needs to be relaunched when PC returns from sleep

### ISSUE THREAD

**Issue by mat4444** [PiotrMachowski/Home-Assistant-Taskbar-Menu#13]
Hello,
Sorry for reporting something else again :)
Whenever one of my PC returns from sleep mode, the Taskbar is unusable : the taskbar will show "Reconnect" instead of listing the entities. Clicking on Reconnect does not do anything.
I need to close the app and relaunch it again. 
Is there a workaround ? 
Thank you

**Comment by PiotrMachowski** [comment]
I have fixed this problem in v1.1.2.0
