### ISSUE TITLE
Issue: can't change brightness, color, temperature of light group

### ISSUE THREAD

**Issue by mat4444** [PiotrMachowski/Home-Assistant-Taskbar-Menu#17]
Hello,
In version 1.2.0, it's not possible to change the brightness/color/temperature of a light group. I don't know if it's an issue linked to a recent update of H.A or if it's a bug with the new version of the taskbar.
Would it be possible to fix it anyway ?
Thanks !

**Comment by PiotrMachowski** [comment]
I think it is a problem witch changes in light platform that were introduced in HA 2021.5. I will make a fix soon (I hope) :)

**Comment by mat4444** [comment]
Thanks for acknowledging it !

**Comment by Morgane-dotcom** [comment]
I also noticed this problem. Do you have an idea of when you'll be able to look into this ? Thank you, this is a really cool Windows app !

**Comment by PiotrMachowski** [comment]
Finally managed to get my hands on it, fix coming soon :)

**Comment by PiotrMachowski** [comment]
Added in v1.2.1.0

**Comment by mat4444** [comment]
Cool :) Thanks for this bug fixing !
