### ISSUE TITLE
Split menus to left and right click

### ISSUE THREAD

**Issue by noxhirsch** [PiotrMachowski/Home-Assistant-Taskbar-Menu#2]
What do you think of splitting the menu:
Left click: Show entities
Right click: Config/Exit/...

This is the behaviour of most apps in the taskbar:
Left click: Action (open app or popup)
Right click: Settings & Exit
(Example: Bitwarden, MS Teams, Teamviewer, OneDrive, Flux and many more)

This would make the entities view cleaner and you don't have to move the mouse that much.

**Comment by PiotrMachowski** [comment]
Splitting to two context menus would require a library change, what do you think about this solution?

![image](https://user-images.githubusercontent.com/6118709/86028644-6e4ea380-ba32-11ea-8cbb-ff87e48c01a1.png)

**Comment by noxhirsch** [comment]
I think that's a very good comprimise 👍

**Comment by PiotrMachowski** [comment]
New UI is available in v1.0.1.0
