### ISSUE TITLE
Add new Entity types

### ISSUE THREAD

**Issue by NinFanBoyFTW** [PiotrMachowski/Home-Assistant-Taskbar-Menu#27]
Hi, I have been loving your program for about a year now. I just switched all of my scene based automation over to the new ""input_buton" helper that Home assistant introduced. I wanted to know if it would be possible to add these and all of the new similar entities to the white list as I cannot see them on the list anymore and they don't work with the current revision. Thanks again

**Comment by PiotrMachowski** [comment]
Added in 1.3.0.0
