### ISSUE TITLE
Token needed 

### ISSUE THREAD

**Issue by MiAutomations** [PiotrMachowski/Home-Assistant-Taskbar-Menu#3]
Hello 

First of all thank you for your great job!! :)

Can you please let me know where I can get the token to perform the connection ?

Thank you and best regards

**Comment by PiotrMachowski** [comment]
Hi,

You can create it in your HA [profile](https://www.home-assistant.io/docs/authentication/#your-account-profile)

**Comment by MiAutomations** [comment]
Great thank you is now configured,

But now I'm not able to launch the app I double click on the icon and nothing occurs, can you please help me in order to try solve this issue? 

Thank you and best regards

**Comment by PiotrMachowski** [comment]
App icon should be visible in your system tray

**Comment by MiAutomations** [comment]
> ould be visible in your system tray

Yes I know, but is not, and also I doesn't see this in the task manager ...

**Comment by PiotrMachowski** [comment]
Check `%APPDATA%/Home Assistant Taskbar Menu` directory if configuration file is present

**Comment by MiAutomations** [comment]
> Check `%APPDATA%/Home Assistant Taskbar Menu` directory if configuration file is present

Yes it's present  this one config_credentials.dat

**Comment by PiotrMachowski** [comment]
Which version of windows do you have?

**Comment by MiAutomations** [comment]
> Which version of Windows do you have?

Windows 10

**Comment by MiAutomations** [comment]
> Which version of Windows do you have?

Any ideia to solve this issue? 

Thank you

**Comment by PiotrMachowski** [comment]
Working on it

**Comment by MiAutomations** [comment]
> Working on it

Great thank you

**Comment by PiotrMachowski** [comment]
Please try using the latest version and check `log.txt` file

**Comment by MiAutomations** [comment]
> Please try using the latest version and check `log.txt` file

I just install the new versions available Home_Assistant_Taskbar_Menu_Installer_v1.1.1.0 and the problem persist 

Can you please help me in order to solve this issue ?
