### ISSUE TITLE
Dark Theme No being applied

### ISSUE THREAD

**Issue by 9812ga98sd** [PiotrMachowski/Home-Assistant-Taskbar-Menu#35]
When I apply the dark theme it shows the taskbar menu dark with white text but home assistant window is blue and white. I've restarted the app and there is no change.

**Comment by PiotrMachowski** [comment]
Dark theme is applied only for application itself, to change HA window you have to adjust HA settings

**Comment by 9812ga98sd** [comment]
HA is set to dark theme. The application is set to dark. It still shows white only in the application, the menus for the application are dark.

**Comment by PiotrMachowski** [comment]
How have you set dark theme for HA?

**Comment by 9812ga98sd** [comment]
Please see the message before:
"HA is set to dark theme. "
"The application is set to dark" theme.

**Comment by PiotrMachowski** [comment]
Yes. I'm asking how have you enabled dark theme in HA.

It usually has to be done for each browser separately, so you have to go to HA settings in Taskbar Menu browser and change it there as well.
