### ISSUE TITLE
Right Click Menu on taskbar icon are Flickering & cannot select any icons can see Reconnect & 5 icons

### ISSUE THREAD

**Issue by theshop35** [PiotrMachowski/Home-Assistant-Taskbar-Menu#37]
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:80
Integration: HTTP (documentation, issues)
First occurred: 12:48:38 (130432 occurrences)
Last logged: 14:35:54

Login attempt or request with invalid authentication from fe80::a236:8dd6:4509:5bfc (fe80::a236:8dd6:4509:5bfc). Requested URL: '/api/websocket'. (None)
Login attempt or request with invalid authentication from 192.168.31.101 (192.168.31.101). Requested URL: '/api/websocket'. (None)

**Comment by mat4444** [comment]
Hi, how did you fix this?
